char *genver=
"__VERSION_H__\n"
"_NEW_SERVER_\n"
"_SERVER_NUMS\n"
"SERVER_VERSION '龙zoro版GMSV服务端v2.2.2.28'\n"
"UNIQUE_KEYCODEITEM	100\n"
"UNIQUE_KEYCODEPET	'i'\n"
"_SA_VERSION_70              // (可开放) WON ADD 石器时代7.0 的版本控制\n"
"_DEFAULT_PKEY 'ttttttttt'   // (可开放)( 石器 6.0 )\n"
"_RUNNING_KEY  '20041215'    // (可开放)( 石器 6.0 )\n"
"_VERSION_20010911           // (可开放) 9.11 编码修改 \n"
"_TEST_PETCREATE             // (不可开) ANDY 测宠的GM指令\n"
"_FAMILY_MANORNUM_CHANGE	 // CoolFish 用来修改装园数量(4.0)\n"
"FAMILY_MAXHOME 10        // (4.0) 家族据点\n"
"MANORNUM 10              // (4.0) 庄园数量\n"
"FMPOINTNUM 10            // (4.0) 有据点家族的最大数量\n"
"_FMVER21                 // (可开放) 家族职掌功能  \n"
"_PERSONAL_FAME           // (可开放) Arminius 8.30 家族个人声望  \n"
"_SERVICE                 // (可开放) Terry 2001/10/03 活动功能自动化 \n"
"_EVERYONE_RIDE           // (可开放) Robin 0924 骑宠平民化  \n"
"__ATTACK_MAGIC           // (可开放)	提供战场中的攻击性咒术\n"
"_ADD_ACTION              // (可开放) 一般NPC动作状况的设定\n"
"_UNIQUE_P_I              // (可开放) CoolFish 2001/10/11 \n"
"_NEWSAVE                 // (可开放) Robin\n"
"_STORECHAR               // (可开放) Robin\n"
"_DROPCHECK               // (可开放) Robin 防止重复丢道具\n"
"_DROPCHECK2              // (可开放) Robin 防止重复丢道具\n"
"_PET_TRANS               // (可开放) 宠物转生功能\n"
"_NEW_WARPMAN             // (可开放) NPC多重WARP功能\n"
"_PET_TALK                // (可开放) 宠物对话\n"
"_PET_LIMITLEVEL          // (可开放) 特殊宠设计(玛蕾)\n"
"_MAP_NOEXIT              // (可开放) 特殊地图不得原登&原登回指定点\n"
"_GMRELOAD                // (可开放) CoolFish: 2001/11/12 \n"
"_GAMBLE_ROULETTE         // (可开放) 彦豪 赌场轮盘	宝宝小猪  \n"
"_FIX_GAMBLENUM           // (可开放) 轮盘修正 : 下线扣积分 \n"
"_GAMBLE_BANK             // (可开放) 彦豪  赌场银行  \n"
"_DROPSTAKENEW            // (可开放) CoolFish:  赌场下注  \n"
"_PETRACE                 // (可开放) CoolFish: 2001/12/3 宠物竞速场  \n"
"_NEWEVENT                // (可开放) CoolFish: 2001/12/5 新的任务旗标  \n"
"_ITEM_FIRECRACKER        // (可开放) 战斗中使用鞭炮可以把年兽吓走\n"
"_MANOR_PKRULE            // (可开放)\n"
"_MANOR_FIXFMPK           // (可开放) WON ADD 家族约战的 GM 指令，测试用的\n"
"_PSKILL_FALLGROUND       // (可开放) 宠物技能  (落马术)\n"
"_ENEMY_FALLGROUND        // (可开放) NPC 落马\n"
"_BATTLE_NEWPOWER         // (可开放)\n"
"_Item_MoonAct            // (可开放) 月神的守护\n"
"_Item_DeathAct           // (可开放) 恶魔的首饰\n"
"_Item_PetAct             // (可开放) 驯兽戒指\n"
"_Item_ReLifeAct          // (可开放) 需要itemset1.txt 才能开) 替身娃娃\n"
"_BATTLESTEAL_FIX         // (可开放) 修正偷窃\n"
"_CFREE_petskill          // (可开放) 需要petskill1.txt 才能开) 新学习宠物技能技能\n"
"_data_newreadfile        // (可开放) 新的server setup.cf 档案 包含 itemset1.txt petskill1.txt 两个新档\n"
"_ITEM_MAXUSERNUM         // (可开放) 新 itemset1.txt ITEM 使用次数\n"
"_PET_TALKPRO             // (可开放) 宠物对话加强  & 改 END\n"
"_PRO_NPCFIX              // (可开放) NPC功能加强\n"
"_PRO_BATTLEENEMYSKILL    // (可开放) 战斗加强  提升NPC的AI技能\n"
"_NEW_WARPPOINT           // (可开放) 传送点多重条件判断WARP\n"
"_FIX_CHECKITEM           // (可开放) 道具不做非法检查\n"
"_ADD_ENCOUNT             // (可开放) WON 增加敌遭遇触发修件 \n"
"_WON_PET_MAIL_LOG        // (可开放) WON 玩家寄宠邮 LOG \n"
"_FIX_FAMILY_PK_LIMIT     // (可开放) WON 将可挑战庄园的由前十大改为前二十大\n"
"_ADD_POOL_ITEM           // (可开放) WON 增加可寄放的道具\n"
"_ITEM_METAMO             // (可开放) shan metamo sprite. code:robin->shan\n"
"_ENEMY_ATTACK_AI         // (可开放) shan enemy attack mode. code:shan  \n"
"_ITEM_TIME_LIMIT         // (可开放) shan time limit of item. code:shan\n"
"_MIND_ICON               // (可开放) shan show icon from char mind. code:shan\n"
"_BATTLENPC_WARP_PLAYER   // (可开放) shan npc warp player when n round. code:shan\n"
"_ITEM_WARP_FIX_BI        // (可开放) shan fix bbi to bi. code:shan\n"
"_SKILL_DAMAGETOHP        // (可开放) ANDY 嗜血技 \n"
"_Skill_MPDAMAGE          // (可开放) ANDY MP伤害\n"
"_WAEI_KICK               // (可开放) ANDY 跨星球踢人\n"
"_BATTLE_TIMESPEED        // (可开放) ANDY 战斗时间 测试(北京不必开，挡加速功能)\n"
"_NEW_RIDEPETS            // (可开放) ANDY 新骑宠\n"
"_FIXBUG_ATTACKBOW        // (可开放) ANDY 修正骑宠使用投掷武器bug\n"
"_NPCCHANGE_PLAYERIMG     // (可开放) ANDY NPC改变玩家图号, 强制落马,认玩家图号 (测完)\n"
"_ITEM_ATTSKILLMAGIC      // (可开放) ANDY 道具技能  \n"
"_EQUIT_DEFMAGIC          // (可开放) ANDY 抗魔装备\n"
"_FIX_MAGICDAMAGE         // (可开放) ANDY 修正魔法公式 叁期开放\n"
"_ITEM_CONSTITUTION       // (可开放) ANDY 修正个人体质\n"
"_MAGIC_REHPAI            // (可开放) ANDY 补血AI\n"
"_TRANSER_MAN             // (可开放) ANDY 传送师\n"
"_TAKE_ITEMDAMAGE         // (可开放) ANDY 道具损坏  ITEMSET2\n"
"_FIX_FIRECRACKER         // (可开放) ANDY 修正 鞭炮\n"
"_FIX_ITEMPROB            // (可开放) ANDY 修正 掉宝率\n"
"_ADD_DEAMGEDEFC          // (可开放) ANDY 额外伤害 & 附加攻击  ITEMSET2\n"
"_FIX_MAXCHARMP           // (可开放) ANDY MP上限\n"
"_ITEM_INSLAY             // (可开放) ANDY 镶宝石 动作\n"
"_ITEMSET2_ITEM           // (可开放) ANDY ITEMSET2\n"
"_ITEM_NPCCHANGE          // (可开放) ANDY 工匠 (提炼, 精工)\n"
"_PETSKILL_FIXITEM        // (可开放) ANDY 修复 && 同道具损坏\n"
"_FIX_SETWORKINT          // (可开放) ANDY (FIXWORKINT)\n"
"_ITEM_ADDEXP             // (可开放) vincent  道具:指定时间内增加经验值上升幅度\n"
"_ITEM_ADDEXP2            // 智果时间可以累加 Robin\n"
"_FIX_METAMORIDE          // (可开放) ANDY\n"
"_CHECK_ITEMDAMAGE        // (可开放) 道具损坏修正  7/26\n"
"_SKILL_WILDVIOLENT_ATT   // (可开放) vincent  宠技:狂暴攻击\n"
"_MAGIC_WEAKEN            // (可开放) vincent  精灵:虚弱\n"
"_SKILL_WEAKEN            // (可开放) vincent  宠技:虚弱//需要开#define _MAGIC_WEAKEN\n"
"_SKILL_SPEEDY_ATT        // (可开放) vincent  宠技:疾速攻击\n"
"_SKILL_GUARDBREAK2       // (可开放) vincent  宠技:破除防御2\n"
"_SKILL_SACRIFICE         // (可开放) vincent  宠技:救援\n"
"_PSKILL_MODIFY           // (可开放) ANDY 属性强化攻击\n"
"_PSKILL_MDFYATTACK       // (可开放) ANDY 攻击转化属性\n"
"_MAGIC_DEFMAGICATT       // (可开放) ANDY 魔法防御\n"
"_MAGIC_SUPERWALL         // (可开放) ANDY 铁壁防御\n"
"_OTHER_MAGICSTAUTS       // (可开放) ANDY \n"
"_SKILL_TOOTH             // (可开放) ANDY   齿术\n"
"_MAGIC_DEEPPOISON        // (可开放) vincent  精灵:剧毒\n"
"_MAGIC_BARRIER           // (可开放) vincent  精灵:魔障\n"
"_MAGIC_NOCAST            // (可开放) vincent  精灵:沉默\n"
"_ITEM_CRACKER            // (可开放) vincent  道具:拉炮 //需要开#define _MIND_ICON\n"
"_SKILL_DEEPPOISON        // (可开放) vincent  宠技:剧毒 //需要开#define _MAGIC_DEEPPOISON\n"
"_SKILL_BARRIER           // (可开放) vincent  宠技:魔障 //需要开#define _MAGIC_BARRIER\n"
"_SKILL_NOCAST            // (可开放) vincent  宠技:沉默 //需要开#define _MAGIC_NOCAST\n"
"_SKILL_ROAR              // (可开放) vincent  宠技:大吼(克年兽)\n"
"_SKILL_REFRESH           // (可开放) vincent  宠技:解除异常状态\n"
"_ITEM_REFRESH            // (可开放) vincent  解除异常状态道具\n"
"_MAGIC_TOCALL            // (可开放) kjl     召唤  02/06/20 kjl  \n"
"_ITEMSET3_ITEM           // (可开放) ANDY itemset3.txt\n"
"_SUIT_ITEM               // (可开放) ANDY (套装) 来吉卡 需用itemset3.txt\n"
"_PETSKILL_SETDUCK        // (可开放) ANDY 蒙奇技能\n"
"_VARY_WOLF               // (可开放) pet skill : vary wolf. code:shan\n"
"_USEWARP_FORNUM          // (可开放) ANDY 记忆羽毛 来吉卡\n"
"_IMPRECATE_ITEM          // (可开放) ANDY 特殊道具 来吉卡\n"
"_MAGICPET_SKILL          // (可开放) ANDY 魔法宠技能\n"
"_ITEM_CHECKWARES         // (可开放) ANDY 锁定传送不能\n"
"_NPC_REPLACEMENT         // (可开放) ANDY 置换战斗npc\n"
"_EMENY_CHANCEMAN         // (可开放) ANDY EMENY 选择\n"
"_TYPE_TOXICATION         // (可开放) ANDY 中毒无法回血\n"
"_PET_FUSION              // (可开放) ANDY 宠物融合 enemybase1.txt\n"
"_NPC_FUSION              // (可开放) ANDY NPC宠物融合\n"
"_ITEM_EDITBASES          // (可开放) ANDY 营养剂\n"
"_PET_EVOLUTION           // (可开放) ANDY 进化表\n"
"_AVID_TRADETRYBUG        // (可开放) ANDY 防止交易中丢宠/道具 寄(宠物)邮件 石币\n"
"_ASSESS_SYSEFFICACY      // (可开放) ANDY 评估系统效能 12/04 更新\n"
"_ASSESS_SYSEFFICACY_SUB  // (可开放) Robin 评估系统效能 增加检查内回圈\n"
"_PREVENT_TEAMATTACK      // (可开放) ANDY 防止同队互打 12/04 更新\n"
"_ITEM_ORNAMENTS          // (可开放) ANDY 装饰道具  12/04 更新  //出版部\n"
"_CHIKULA_STONE           // (可开放) ANDY 奇克拉之石 12/04 更新  //来吉卡 宠包\n"
"_SEND_EFFECT             // (可开放) WON  AC送下雪、下雨等特效 12/04 更新\n"
"_PETMAIL_DEFNUMS         // (可开放) ANDY 宠物邮件限制\n"
"_TEAM_KICKPARTY          // (可开放) ANDY 队长踢人(非战斗状态)\n"
"_PETSKILL_TIMID          // (可开放) ANDY 宠技-怯战\n"
"_PETS_SELECTCON          // (可开放) ANDY 宠物不可点选出战\n"
"_CHRISTMAS_REDSOCKS      // (可开放) ANDY 圣诞红袜\n"
"_FIX_ARRAYBUG            // (可开放) ANDY 修正array 溢位\n"
"_USER_CHARLOOPS          // (可开放) ANDY 新用物件LOOP\n"
"_BATTLE_PROPERTY         // (可开放) ANDY 战斗属性特性\n"
"_PETSKILL_PROPERTY       // (可开放) ANDY 无属魔兽宠技\n"
"_ITEM_FIXALLBASE         // (可开放) ANDY 修复之石\n"
"_ITEM_LOVERPARTY         // (可开放) ANDY 情人节道具\n"
"_ITEM_FORUSERNAMES       // (可开放) ANDY 道具所有人\n"
"_BATTLECOMMAND_TIME      // (可开放) ANDY 防止玩家开缓速(回合战斗时间)\n"
"_NPCENEMY_ADDPOWER       // (可开放) ANDY 修改怪物的能力值\n"
"_PETSKILL_CANNEDFOOD     // (可开放) ANDY 宠物技能罐头  for 6.0\n"
"_TEST_DROPITEMS          // (可开放) ANDY 测试丢宠\n"
"_MAP_WARPPOINT           // (可开放) ANDY Map WarpPoint\n"
"_DEFEND_TIMECHECK        // (可开放) ANDY 内部测试时间\n"
"_TREASURE_BOX            // (可开放) ANDY 宝箱\n"
"_BENEMY_EVENTRUN         // (可开放) ANDY 战斗npc给道具\n"
"_BATTLE_ABDUCTII         // (可开放) ANDY 旅途夥伴2\n"
"_BATTLE_LIGHTTAKE        // (可开放) ANDY 采光术\n"
"_BATTLE_ATTCRAZED        // (可开放) ANDY 疯狂暴走\n"
"_STATUS_WATERWORD        // (可开放) ANDY 水世界状态\n"
"_ITEM_WATERWORDSTATUS    // (可开放) ANDY 水世界状态道具\n"
"_REEDIT_PETBBIS          // (可开放) ANDY 修正宠物波比图形\n"
"_CAPTURE_FREES           // (可开放) ANDY 补抓条件\n"
"_THROWITEM_ITEMS         // (可开放) 丢掷後有奖品\n"
"_OBJSEND_C               // (可开放) ANDY _OBJSEND_C\n"
"_ADD_SHOW_ITEMDAMAGE     // (可开放) WON  显示物品耐久度\n"
"_CHANGETRADERULE         // (可开放) Syu ADD 交易规则修订\n"
"_TRADE_SHOWHP            // (可开放) Syu ADD 交易显示血量\n"
"_SHOOTCHESTNUT           // (可开放) Syu ADD 宠技：丢栗子\n"
"_SKILLLIMIT              // (可开放) Syu ADD 不得攻击我方限制\n"
"_TRADESYSTEM2            // (可开放) Syu ADD 新交易系统\n"
"_NPC_NOSAVEPOINT         // (可开放) ANDY 纪录点不存人物资料\n"
"_ACFMPK_LIST             // (可开放) ANDY 家族对战列表修正\n"
"_PETSKILL2_TXT           // (可开放) ANDY petskill2.txt\n"
"_PETSKILL_CHECKTYPE      // (可开放) ANDY 宠物技能使用时机\n"
"_PETSKILL_TEAR           // (可开放) ANDY 宠技 撕裂伤口\n"
"_NPC_MAKEPAIR            // (可开放) ANDY NPC 配对\n"
"_ITEMSET4_TXT            // (可开放) ANDY itemset4.txt\n"
"_ITEM_PILENUMS           // (可开放) ANDY 道具素材堆叠 需 itemset4\n"
"_ITEM_PILEFORTRADE       // (可开放) ANDY 交易堆叠\n"
"_ITEM_EQUITSPACE         // (可开放) ANDY 新装备栏位\n"
"_PET_LOSTPET             // (可开放) ANDY 遗失宠物搜寻计划宠物\n"
"_ITEMSET5_TXT            // (可开放) ANDY itemset5.txt\n"
"_ITEMSET6_TXT            // (可开放) ANDY itemset6.txt\n"
"_EQUIT_ARRANGE           // (可开放) ANDY 挡格 需要 itemset5.txt\n"
"_EQUIT_SEQUENCE          // (可开放) ANDY 攻击顺序 需要 itemset5.txt\n"
"_EQUIT_ADDPILE           // (可开放) ANDY 增加可堆叠数 需要 itemset5.txt\n"
"_EQUIT_HITRIGHT          // (可开放) ANDY 命中 需要 itemset5.txt\n"
"_EQUIT_NEGLECTGUARD      // (可开放) ANDY 忽视目标防御力% 需要 itemset6.txt\n"
"_EQUIT_NEWGLOVE          // (可开放) ANDY 手套栏位\n"
"_FM_JOINLIMIT            // (可开放) ANDY 加入家族条件限制\n"
"_FIX_MAX_GOLD            // (可开放) WON ADD 增加人物金钱上限 \n"
"_CK_ONLINE_PLAYER_COUNT  // (可开放) WON 计算线上人数 (要配合ac，否则会重开)  \n"
"_PET_SKILL_SARS          // (可开放) WON ADD 毒煞蔓延\n"
"_SONIC_ATTACK            // (可开放) WON ADD 音波攻击\n"
"_NET_REDUCESEND          // (可开放) ANDY 减少DB资料传送\n"
"_FEV_ADD_NEW_ITEM        // (可开放) Change 增加复活守精\n"
"_ALLDOMAN                // (可开放) Syu ADD 排行榜NPC\n"
"_LOCKHELP_OK             // (可开放) Syu ADD 锁定不可加入战斗\n"
"_TELLCHANNEL             // (可开放) Syu ADD 密语频道\n"
"_NEWREQUESTPROTOCOL      // (可开放) Syu ADD 新增Protocol要求细项\n"
"_OUTOFBATTLESKILL        // (可开放) Syu ADD 非战斗时技能Protocol\n"
"_CHAR_PROFESSION         // (可开放) WON ADD 人物职业栏位\n"
"_PROFESSION_SKILL        // (可开放) WON ADD 人物职业技能\n"
"_NPC_WELFARE             // (可开放) WON ADD 职业NPC\n"
"_PROFESSION_FIX_LEVEL    // (可开放) WON ADD 修正职业经验值(北京&韩国不必开)\n"
"_GM_SIGUSR2              // (可开放) Change 下达sigusr2後执行 gm_sigusr_command档案内的GM指令,若没有指令就关闭GMSV\n"
"_GM_BROADCAST            // (可开放) WON ADD 客服公告系统\n"
"_NPC_ADDLEVELUP          // (可开放) ANDY NPC增加玩家等级\n"
"_CHAR_FIXDATADEF         // (可开放) ANDY 修正人物资料初始\n"
"_SIMPLIFY_ITEMSTRING     // (可开放) ANDY 简化道具字串\n"
"_CHAR_NEWLOGOUT          // (可开放) ANDY 登出新机制\n"
"_CHATROOMPROTOCOL        // (可开放) Syu ADD 聊天室频道 8/27\n"
"_CHAR_POOLITEM           // (可开放) ANDY 人物道具仓库共用\n"
"_NPC_DEPOTITEM           // (可开放) ANDY 人物道具仓库共用\n"
"_SIMPLIFY_PETSTRING      // (可开放) ANDY 简化宠物存档字串\n"
"_SIMPLIFY_ITEMSTRING2    // (可开放) ANDY 简化道具字串2\n"
"_WOLF_TAKE_AXE           // (可开放) WON ADD 抓双头狼的限制\n"
"_FIX_UNNECESSARY         // (可开放) ANDY 修正不必要的判断\n"
"_ITEM_MAGICRECOVERY      // (可开放) ANDY 新光镜守\n"
"_PETSKILL_GYRATE         // (可开放) Change 宠技:回旋攻击\n"
"_PETSKILL_ACUPUNCTURE    // (可开放) Change 宠技:针刺外皮 (client端的_PETSKILL_ACUPUNCTURE也要开)\n"
"_PETSKILL_RETRACE        // (可开放) Change 宠技:追迹攻击\n"
"_PETSKILL_HECTOR         // (可开放) Change 宠技:威吓\n"
"_PETSKILL_FIREKILL       // (可开放) Change 宠技:火线猎杀\n"
"_PETSKILL_DAMAGETOHP     // (可开放) Change 宠技:暗月狂狼(嗜血技的变体) \n"
"_PETSKILL_BECOMEFOX      // (可开放) Change 宠技:媚惑术\n"
"_FIX_MESSAGE             // (可开放) WON ADD 修改WORKER封包内容 (北京&韩国不必开)     \n"
"_PETSKILL_SHOWMERCY      // (可开) Change 宠技:手下留情\n"
"_NPC_ActionFreeCmp       // (可开) Change 替NPC参数加入新的比较方式\n"
"_NPC_ProfessionTrans     // (可开) Change 替职业NPC加入判断转生\n"
"_NPC_NewDelPet           // (可开) Change 替NPC加入删除宠物(原本就有了,只是用warpman使用时不成功,所以先做一个顶一下)\n"
"_CHANGEGALAXY            // (可开) 星系移民　Robin 2003/10\n"
"_ALLDOMAN_DEBUG          // (可开) Change 修正重启server後排行榜消失bug\n"
"_CHRISTMAS_REDSOCKS_NEW  // (可开) Change 新圣诞红袜\n"
"_PETSKILL_COMBINED       // (可开) Change 宠技:难得糊涂 [综合魔法(依参数乱数取出魔法)]\n"
"_NPC_ADDWARPMAN1         // (可开放) Change npcgen_warpman增加功能(设定组队人数、设定组队男女人数)\n"
"_ITEM_QUITPARTY          // (可开放) Change 队伍解散时特定道具即会消失\n"
"_ITEM_ADDEQUIPEXP        // (可开) Change 装备後经验值增加\n"
"_ITEM_LVUPUP             // (可开) Change 突破宠物等级限制的药(玄武专用)\n"
"_PETSKILL_BECOMEPIG      // (可开) Change 宠技:乌力化\n"
"_ITEM_UNBECOMEPIG        // (可开) Change 乌力化的解药\n"
"_PET_TALKBBI             // (可开) Change 增加判断bbi\n"
"_ITEM_USEMAGIC           // (可开) Change 由道具使用魔法\n"
"_ITEM_PROPERTY           // (可开) Change 改变四属性道具\n"
"_SUIT_ADDENDUM           // (可开) Change 替套装增加功能 (_SUIT_ITEM要开)\n"
"_ITEM_CHECKDROPATLOGOUT  // (可开) Change 检查回纪录点时身上有无登出後消失道具,若有,不可回纪录点\n"
"_FM_MODIFY               // 家族功能修改(开放)\n"
"_CHANNEL_MODIFY          // 频道功能整合(开放)\n"
"_STANDBYPET              // Robin 待机宠封包\n"
" _PROSKILL_OPTIMUM       // Robin 职业技能处理最佳化\n"
" _PETSKILL_OPTIMUM       // Robin 宠物技能处理最佳化\n"
"_MAGIC_OPTIMUM           // Robin Magic table 最佳化\n"
"_AC_PIORITY              // Nuke 提高AC的优先权(可开)\n"
"_CHAR_POOLPET            // (可开放) Robin 人物宠物仓库共用\n"
"_NPC_DEPOTPET            // (可开放) Robin 人物宠物仓库共用\n"
"_TIMEOUTKICK             // (可开) 时段制踢人　Robin 2003/10\n"
"_MAGIC_RESIST_EQUIT      // (可开) WON ADD 职业抗性装备\n"
"_LOG_OTHER               // 杂项讯息专用LOG\n"
"_NEWOPEN_MAXEXP          // (可开) ANDY MAX经验值\n"
"_REDHAT_V9               //(可开) Change 在REDHAT9.0的版本下编译时打开\n"
"_NPC_EXCHANGEMANTRANS    // (可开) Change 替exchangeman加入判断转生\n"
" _ANGEL_SUMMON           // Robin 天使召唤\n"
"_STREET_VENDOR           // 摆摊功能(开放)\n"
"_WATCH_EVENT             // 查询任务功能(开放)\n"
"_NEW_MANOR_LAW           // 新庄园规则(开放)\n"
"_MAP_TIME                // 特殊地图,会倒数(开放)\n"
"_PETSKILL_LER            // 雷尔技能(开放)\n"
"_TEACHER_SYSTEM          // 导师系统(开放)\n"
"_FIX_MAGIC_RESIST        // (可开) Change 职业魔法抗性\n"
"_ADD_DUNGEON             // (可开) Change 追加地牢\n"
"_PROFESSION_ADDSKILL     // (可开) Change 追加职业技能\n"
"_ITEM_ADDPETEXP          // (可开) Change 增加宠物经验值道具(可吃此道具宠物,平常不可获得经验值)\n"
"_TRANS_6                 // (可开) Change 人物6转\n"
"_TRANS_7                 // (可开) Change 人物7转\n"
"_PET_2TRANS              // (可开) Change 宠物2转\n"
"_PET_2LIMITLEVEL         // (可开) Change 帮助宠物2转的玛蕾\n"
"_MAGICSTAUTS_RESIST      // (可开) Change (火电冰)抗性精灵\n"
"_EQUIT_RESIST            // (可开) Change 单一装备抗性(可抗单一功能异常状态)有抗火 雷 冰 虚弱 魔障 沉默 落马\n"
"_SUIT_TWFWENDUM          // (可开) Change 四属性套装功能 (_SUIT_ITEM要开)\n"
"_EXCHANGEMAN_REQUEST_DELPET   // (可开) Change 替exchangeman的TYPE:REQUEST增加删除宠物\n"
"_ESCAPE_RESET            // 恶宝逃跑後暂时不可组队  Robin 2004/07/22\n"
"_DEL_DROP_GOLD           // 删除地上过时的石币  Robin\n"
"_ITEM_STONE              // cyg 奇怪的石头\n"
"_HELP_NEWHAND            // cyg 新创角色给予新手道具)\n"
"_DEF_FMFREETIME          // cyg GM指令 退出家族时间限制设为0\n"
"_DEF_GETYOU              // cyg GM指令 查询自己两格  围内的玩家帐号\n"
"_DEF_NEWSEND             // cyg GM指令 传送玩家时可加句子也可不加\n"
"_DEF_SUPERSEND           // cyg GM指令 可传送已某帐号为中心附近3格内所有玩家\n"
"_SUIT_ADDPART3           // (可开) Change 套装功能第叁弹 回避提高% 沉默抗性提高% 敏提高% 防提高% 攻提高%\n"
"_PETSKILL_2TIMID         // (可开) Change 怯战第二版(狂狮怒吼)\n"
"CAVALRY_DEBUG            // (暂时开) Change 座骑攻击除错中\n"
"_SHOW_FUSION             // (可开) Change 融合宠物在CLIENT端只显示转生数,修改为融合宠显示为融合(client端也要开)\n"
"_CONTRACT                // (可开) Robin 契约功能 \n"
"_FONT_SIZE               // (可开) Robin 字型大小功能\n"
"_PROSK99                 // (可开) Change 检查职技等级送白狼\n"
"_TIME_TICKET             // Robin 限时入场 森林捉宠用\n"
"_HALLOWEEN_EFFECT        // 万圣节特效\n"
"_ADD_STATUS_2            // 新增传送人物状态第二类\n"
"_ADD_reITEM              // (可开) Change 检查道具栏位空格\n"
"_ADD_NOITEM_BATTLE       // 新增NPC检查人物身上没道具会进入战斗\n"
"_PETSKILL_BATTLE_MODEL   // 宠物技能战斗模组\n"
"_RACEMAN                 // cyg 猎宠大会新npc\n"
"_PETSKILL_ANTINTER       // (可开) Change 宠技:蚁之葬 参考_PETSKILL_2TIMID\n"
"_PETSKILL_REGRET         // (可开) Change 宠技:憾甲一击 参考_SONIC_ATTACK\n"
"_SUIT_ADDPART4           // (可开) Change 套装功能第四弹 中毒攻击% 加强法师魔法(机率30%) 抵抗法师的魔法\n"
"_ITEM_SETLOVER           // 结婚功能\n"
"_CREATE_MM_1_2           // 制作极品玛蕾菲雅\n"
"_SendTo                  // 传送到玩家身边\n"
"_GET_BATTLE_EXP          // 经验设置\n"
"_USER_EXP_CF             // 用户自定义经验\n"
"_TRANS_LEVEL_CF          // 转生超越160级设置\n"
"_UNLAW_WARP_FLOOR        // 禁止传送地区\n"
"_UNREG_NEMA              // 禁止人物名称\n"
"_GM_ITEM                 // 玩家GM命令物品\n"
"_GM_METAMO_RIDE          // GM人物骑所有宠\n"
"_GM_RIDE                 // GM命令设置骑宠权限\n"
"_LOCK_IP                 // 锁定IP\n"
"<<Generated at Mon Aug 13 00:53:29 PDT 2018>>"
"by : 龙zoro工作室";
