INCFLAGS=-I.. -I../include


CFLAGS=-w -O3 $(INCFLAGS)

PROG=libchar.a

SRC=char_base.c char.c char_event.c char_data.c skill.c title.c\
addressbook.c chatmagic.c event.c char_walk.c encount.c pet.c \
enemy.c pet_event.c char_talk.c char_party.c char_item.c deathcontend.c \
chatroom.c petmail.c trade.c family.c defend.c char_angel.c

OBJ=$(SRC:.c=.o)

ifeq (0,$(MAKELEVEL))
CC=gcc
RM=rm -f
AR=ar cr
MV=mv
RANLIB=ranlib
SED=sed
SHELL=/bin/sh
endif

all: $(PROG)

$(PROG): $(OBJ)
	$(RM) $(PROG)
	$(AR) $(PROG) $(OBJ)
	$(RANLIB) $(PROG)

depend:
	$(MV) makefile makefile.bak
	$(SED) -ne '1,/^# DO NOT DELETE THIS LINE/p' makefile.bak>makefile
	$(CC) $(INCFLAGS) -M $(SRC) >> makefile 

clean:
	$(RM) $(PROG)
	$(RM) $(OBJ)
	$(RM) *~

distclean:
	$(RM) $(PROG)
	$(RM) $(OBJ)
	$(RM) *~
	$(MV) makefile makefile.bak
	$(SED) -ne '1,/^# DO NOT DELETE THIS LINE/p' makefile.bak>makefile
	$(RM) makefile.bak

# DO NOT DELETE THIS LINE
char_base.o: char_base.c /usr/include/string.h /usr/include/features.h \
 /usr/include/sys/cdefs.h /usr/include/gnu/stubs.h \
 /usr/lib/gcc-lib/i386-redhat-linux/3.2.2/include/stddef.h \
 ../include/char_base.h ../include/skill.h ../include/common.h \
 /usr/include/stdio.h \
 /usr/lib/gcc-lib/i386-redhat-linux/3.2.2/include/stdarg.h \
 /usr/include/bits/types.h /usr/include/libio.h \
 /usr/include/_G_config.h /usr/include/bits/stdio_lim.h \
 ../include/util.h /usr/include/sys/time.h /usr/include/time.h \
 /usr/include/bits/time.h /usr/include/sys/select.h \
 /usr/include/bits/select.h /usr/include/bits/sigset.h \
 /usr/include/stdlib.h /usr/include/sys/types.h /usr/include/endian.h \
 /usr/include/bits/endian.h /usr/include/sys/sysmacros.h \
 /usr/include/alloca.h ../include/title.h ../include/addressbook.h \
 ../include/net.h /usr/include/netinet/in.h \
 /usr/lib/gcc-lib/i386-redhat-linux/3.2.2/include/limits.h \
 /usr/lib/gcc-lib/i386-redhat-linux/3.2.2/include/syslimits.h \
 /usr/include/limits.h /usr/include/bits/posix1_lim.h \
 /usr/include/bits/local_lim.h /usr/include/linux/limits.h \
 /usr/include/bits/posix2_lim.h /usr/include/stdint.h \
 /usr/include/bits/wordsize.h /usr/include/bits/socket.h \
 /usr/include/bits/sockaddr.h /usr/include/asm/socket.h \
 /usr/include/asm/sockios.h /usr/include/bits/in.h \
 /usr/include/bits/byteswap.h /usr/include/signal.h \
 /usr/include/bits/signum.h /usr/include/bits/siginfo.h \
 /usr/include/bits/sigaction.h /usr/include/bits/sigcontext.h \
 /usr/include/asm/sigcontext.h /usr/include/bits/sigstack.h \
 ../include/link.h ../include/char_data.h ../include/item.h \
 ../include/char.h ../include/buf.h ../include/magic.h \
 ../include/function.h ../include/npccreate.h ../include/configfile.h \
 ../include/pet.h ../include/pet_skill.h
char.o: char.c /usr/include/stdio.h /usr/include/features.h \
 /usr/include/sys/cdefs.h /usr/include/gnu/stubs.h \
 /usr/lib/gcc-lib/i386-redhat-linux/3.2.2/include/stddef.h \
 /usr/lib/gcc-lib/i386-redhat-linux/3.2.2/include/stdarg.h \
 /usr/include/bits/types.h /usr/include/libio.h \
 /usr/include/_G_config.h /usr/include/bits/stdio_lim.h \
 /usr/include/stdlib.h /usr/include/sys/types.h /usr/include/time.h \
 /usr/include/endian.h /usr/include/bits/endian.h \
 /usr/include/sys/select.h /usr/include/bits/select.h \
 /usr/include/bits/sigset.h /usr/include/sys/sysmacros.h \
 /usr/include/alloca.h /usr/include/string.h /usr/include/ctype.h \
 /usr/include/sys/time.h /usr/include/bits/time.h ../include/common.h \
 ../include/char_base.h ../include/skill.h ../include/util.h \
 ../include/title.h ../include/addressbook.h ../include/net.h \
 /usr/include/netinet/in.h \
 /usr/lib/gcc-lib/i386-redhat-linux/3.2.2/include/limits.h \
 /usr/lib/gcc-lib/i386-redhat-linux/3.2.2/include/syslimits.h \
 /usr/include/limits.h /usr/include/bits/posix1_lim.h \
 /usr/include/bits/local_lim.h /usr/include/linux/limits.h \
 /usr/include/bits/posix2_lim.h /usr/include/stdint.h \
 /usr/include/bits/wordsize.h /usr/include/bits/socket.h \
 /usr/include/bits/sockaddr.h /usr/include/asm/socket.h \
 /usr/include/asm/sockios.h /usr/include/bits/in.h \
 /usr/include/bits/byteswap.h /usr/include/signal.h \
 /usr/include/bits/signum.h /usr/include/bits/siginfo.h \
 /usr/include/bits/sigaction.h /usr/include/bits/sigcontext.h \
 /usr/include/asm/sigcontext.h /usr/include/bits/sigstack.h \
 ../include/link.h ../include/char_data.h ../include/item.h \
 ../include/char.h ../include/lssproto_serv.h \
 ../include/lssproto_util.h /usr/include/strings.h \
 /usr/include/unistd.h /usr/include/bits/posix_opt.h \
 /usr/include/bits/confname.h /usr/include/getopt.h \
 ../include/item_event.h ../include/buf.h ../include/object.h \
 ../include/map_deal.h ../include/saacproto_cli.h ../include/map_warppoint.h \
 ../include/saacproto_util.h ../include/readmap.h \
 ../include/handletime.h ../include/char_event.h \
 ../include/npccreate.h ../include/magic_base.h ../include/magic.h \
 ../include/chatmagic.h ../include/configfile.h ../include/log.h \
 ../include/anim_tbl.h ../include/encount.h ../include/battle.h \
 ../include/pet_skill.h ../include/enemy.h ../include/npcutil.h \
 ../include/pet.h ../include/family.h
char_event.o: char_event.c /usr/include/ctype.h \
 /usr/include/features.h /usr/include/sys/cdefs.h \
 /usr/include/gnu/stubs.h /usr/include/bits/types.h \
 /usr/lib/gcc-lib/i386-redhat-linux/3.2.2/include/stddef.h \
 /usr/include/endian.h /usr/include/bits/endian.h ../include/common.h \
 /usr/include/stdio.h \
 /usr/lib/gcc-lib/i386-redhat-linux/3.2.2/include/stdarg.h \
 /usr/include/libio.h /usr/include/_G_config.h \
 /usr/include/bits/stdio_lim.h ../include/char.h \
 ../include/char_base.h ../include/skill.h ../include/util.h \
 /usr/include/sys/time.h /usr/include/time.h /usr/include/bits/time.h \
 /usr/include/sys/select.h /usr/include/bits/select.h \
 /usr/include/bits/sigset.h /usr/include/stdlib.h \
 /usr/include/sys/types.h /usr/include/sys/sysmacros.h \
 /usr/include/alloca.h ../include/title.h ../include/addressbook.h \
 ../include/net.h /usr/include/netinet/in.h \
 /usr/lib/gcc-lib/i386-redhat-linux/3.2.2/include/limits.h \
 /usr/lib/gcc-lib/i386-redhat-linux/3.2.2/include/syslimits.h \
 /usr/include/limits.h /usr/include/bits/posix1_lim.h \
 /usr/include/bits/local_lim.h /usr/include/linux/limits.h \
 /usr/include/bits/posix2_lim.h /usr/include/stdint.h \
 /usr/include/bits/wordsize.h /usr/include/bits/socket.h \
 /usr/include/bits/sockaddr.h /usr/include/asm/socket.h \
 /usr/include/asm/sockios.h /usr/include/bits/in.h \
 /usr/include/bits/byteswap.h /usr/include/signal.h \
 /usr/include/bits/signum.h /usr/include/bits/siginfo.h \
 /usr/include/bits/sigaction.h /usr/include/bits/sigcontext.h \
 /usr/include/asm/sigcontext.h /usr/include/bits/sigstack.h \
 ../include/link.h ../include/char_data.h ../include/item.h \
 ../include/item_event.h ../include/object.h \
 ../include/lssproto_serv.h ../include/lssproto_util.h \
 /usr/include/string.h /usr/include/strings.h /usr/include/unistd.h \
 /usr/include/bits/posix_opt.h /usr/include/bits/confname.h \
 /usr/include/getopt.h ../include/readmap.h ../include/map_deal.h \
 ../include/saacproto_cli.h ../include/saacproto_util.h \
 ../include/npccreate.h ../include/handletime.h ../include/anim_tbl.h
char_data.o: char_data.c /usr/include/string.h /usr/include/features.h \
 /usr/include/sys/cdefs.h /usr/include/gnu/stubs.h \
 /usr/lib/gcc-lib/i386-redhat-linux/3.2.2/include/stddef.h \
 /usr/include/math.h /usr/include/bits/huge_val.h \
 /usr/include/bits/mathdef.h /usr/include/bits/mathcalls.h \
 /usr/lib/gcc-lib/i386-redhat-linux/3.2.2/include/float.h \
 ../include/readmap.h ../include/common.h /usr/include/stdio.h \
 /usr/lib/gcc-lib/i386-redhat-linux/3.2.2/include/stdarg.h \
 /usr/include/bits/types.h /usr/include/libio.h \
 /usr/include/_G_config.h /usr/include/bits/stdio_lim.h \
 ../include/util.h /usr/include/sys/time.h /usr/include/time.h \
 /usr/include/bits/time.h /usr/include/sys/select.h \
 /usr/include/bits/select.h /usr/include/bits/sigset.h \
 /usr/include/stdlib.h /usr/include/sys/types.h /usr/include/endian.h \
 /usr/include/bits/endian.h /usr/include/sys/sysmacros.h \
 /usr/include/alloca.h ../include/anim_tbl.h ../include/char.h \
 ../include/char_base.h ../include/skill.h ../include/title.h \
 ../include/addressbook.h ../include/net.h /usr/include/netinet/in.h \
 /usr/lib/gcc-lib/i386-redhat-linux/3.2.2/include/limits.h \
 /usr/lib/gcc-lib/i386-redhat-linux/3.2.2/include/syslimits.h \
 /usr/include/limits.h /usr/include/bits/posix1_lim.h \
 /usr/include/bits/local_lim.h /usr/include/linux/limits.h \
 /usr/include/bits/posix2_lim.h /usr/include/stdint.h \
 /usr/include/bits/wordsize.h /usr/include/bits/socket.h \
 /usr/include/bits/sockaddr.h /usr/include/asm/socket.h \
 /usr/include/asm/sockios.h /usr/include/bits/in.h \
 /usr/include/bits/byteswap.h /usr/include/signal.h \
 /usr/include/bits/signum.h /usr/include/bits/siginfo.h \
 /usr/include/bits/sigaction.h /usr/include/bits/sigcontext.h \
 /usr/include/asm/sigcontext.h /usr/include/bits/sigstack.h \
 ../include/link.h ../include/char_data.h ../include/item.h \
 ../include/buf.h defaultPlayer.h defaultGroundEnemy.h ls2data.h
skill.o: skill.c /usr/include/stdio.h /usr/include/features.h \
 /usr/include/sys/cdefs.h /usr/include/gnu/stubs.h \
 /usr/lib/gcc-lib/i386-redhat-linux/3.2.2/include/stddef.h \
 /usr/lib/gcc-lib/i386-redhat-linux/3.2.2/include/stdarg.h \
 /usr/include/bits/types.h /usr/include/libio.h \
 /usr/include/_G_config.h /usr/include/bits/stdio_lim.h \
 /usr/include/stdlib.h /usr/include/sys/types.h /usr/include/time.h \
 /usr/include/endian.h /usr/include/bits/endian.h \
 /usr/include/sys/select.h /usr/include/bits/select.h \
 /usr/include/bits/sigset.h /usr/include/sys/sysmacros.h \
 /usr/include/alloca.h /usr/include/string.h ../include/skill.h \
 ../include/common.h ../include/util.h /usr/include/sys/time.h \
 /usr/include/bits/time.h ../include/char.h ../include/char_base.h \
 ../include/title.h ../include/addressbook.h ../include/net.h \
 /usr/include/netinet/in.h \
 /usr/lib/gcc-lib/i386-redhat-linux/3.2.2/include/limits.h \
 /usr/lib/gcc-lib/i386-redhat-linux/3.2.2/include/syslimits.h \
 /usr/include/limits.h /usr/include/bits/posix1_lim.h \
 /usr/include/bits/local_lim.h /usr/include/linux/limits.h \
 /usr/include/bits/posix2_lim.h /usr/include/stdint.h \
 /usr/include/bits/wordsize.h /usr/include/bits/socket.h \
 /usr/include/bits/sockaddr.h /usr/include/asm/socket.h \
 /usr/include/asm/sockios.h /usr/include/bits/in.h \
 /usr/include/bits/byteswap.h /usr/include/signal.h \
 /usr/include/bits/signum.h /usr/include/bits/siginfo.h \
 /usr/include/bits/sigaction.h /usr/include/bits/sigcontext.h \
 /usr/include/asm/sigcontext.h /usr/include/bits/sigstack.h \
 ../include/link.h ../include/char_data.h ../include/item.h
title.o: title.c /usr/include/stdio.h /usr/include/features.h \
 /usr/include/sys/cdefs.h /usr/include/gnu/stubs.h \
 /usr/lib/gcc-lib/i386-redhat-linux/3.2.2/include/stddef.h \
 /usr/lib/gcc-lib/i386-redhat-linux/3.2.2/include/stdarg.h \
 /usr/include/bits/types.h /usr/include/libio.h \
 /usr/include/_G_config.h /usr/include/bits/stdio_lim.h \
 /usr/include/stdlib.h /usr/include/sys/types.h /usr/include/time.h \
 /usr/include/endian.h /usr/include/bits/endian.h \
 /usr/include/sys/select.h /usr/include/bits/select.h \
 /usr/include/bits/sigset.h /usr/include/sys/sysmacros.h \
 /usr/include/alloca.h /usr/include/string.h /usr/include/ctype.h \
 ../include/title.h ../include/common.h ../include/util.h \
 /usr/include/sys/time.h /usr/include/bits/time.h ../include/char.h \
 ../include/char_base.h ../include/skill.h ../include/addressbook.h \
 ../include/net.h /usr/include/netinet/in.h \
 /usr/lib/gcc-lib/i386-redhat-linux/3.2.2/include/limits.h \
 /usr/lib/gcc-lib/i386-redhat-linux/3.2.2/include/syslimits.h \
 /usr/include/limits.h /usr/include/bits/posix1_lim.h \
 /usr/include/bits/local_lim.h /usr/include/linux/limits.h \
 /usr/include/bits/posix2_lim.h /usr/include/stdint.h \
 /usr/include/bits/wordsize.h /usr/include/bits/socket.h \
 /usr/include/bits/sockaddr.h /usr/include/asm/socket.h \
 /usr/include/asm/sockios.h /usr/include/bits/in.h \
 /usr/include/bits/byteswap.h /usr/include/signal.h \
 /usr/include/bits/signum.h /usr/include/bits/siginfo.h \
 /usr/include/bits/sigaction.h /usr/include/bits/sigcontext.h \
 /usr/include/asm/sigcontext.h /usr/include/bits/sigstack.h \
 ../include/link.h ../include/char_data.h ../include/item.h \
 ../include/buf.h ../include/configfile.h
addressbook.o: addressbook.c /usr/include/stdio.h \
 /usr/include/features.h /usr/include/sys/cdefs.h \
 /usr/include/gnu/stubs.h \
 /usr/lib/gcc-lib/i386-redhat-linux/3.2.2/include/stddef.h \
 /usr/lib/gcc-lib/i386-redhat-linux/3.2.2/include/stdarg.h \
 /usr/include/bits/types.h /usr/include/libio.h \
 /usr/include/_G_config.h /usr/include/bits/stdio_lim.h \
 /usr/include/stdlib.h /usr/include/sys/types.h /usr/include/time.h \
 /usr/include/endian.h /usr/include/bits/endian.h \
 /usr/include/sys/select.h /usr/include/bits/select.h \
 /usr/include/bits/sigset.h /usr/include/sys/sysmacros.h \
 /usr/include/alloca.h /usr/include/string.h /usr/include/strings.h \
 ../include/addressbook.h ../include/common.h ../include/util.h \
 /usr/include/sys/time.h /usr/include/bits/time.h ../include/net.h \
 /usr/include/netinet/in.h \
 /usr/lib/gcc-lib/i386-redhat-linux/3.2.2/include/limits.h \
 /usr/lib/gcc-lib/i386-redhat-linux/3.2.2/include/syslimits.h \
 /usr/include/limits.h /usr/include/bits/posix1_lim.h \
 /usr/include/bits/local_lim.h /usr/include/linux/limits.h \
 /usr/include/bits/posix2_lim.h /usr/include/stdint.h \
 /usr/include/bits/wordsize.h /usr/include/bits/socket.h \
 /usr/include/bits/sockaddr.h /usr/include/asm/socket.h \
 /usr/include/asm/sockios.h /usr/include/bits/in.h \
 /usr/include/bits/byteswap.h /usr/include/signal.h \
 /usr/include/bits/signum.h /usr/include/bits/siginfo.h \
 /usr/include/bits/sigaction.h /usr/include/bits/sigcontext.h \
 /usr/include/asm/sigcontext.h /usr/include/bits/sigstack.h \
 ../include/link.h ../include/char.h ../include/char_base.h \
 ../include/skill.h ../include/title.h ../include/char_data.h \
 ../include/item.h ../include/handletime.h ../include/buf.h \
 ../include/lssproto_serv.h ../include/lssproto_util.h \
 /usr/include/unistd.h /usr/include/bits/posix_opt.h \
 /usr/include/bits/confname.h /usr/include/getopt.h \
 ../include/saacproto_cli.h ../include/saacproto_util.h \
 ../include/object.h ../include/battle.h ../include/configfile.h \
 ../include/npcutil.h ../include/pet.h ../include/petmail.h \
 ../include/log.h
chatmagic.o: chatmagic.c /usr/include/stdio.h /usr/include/features.h \
 /usr/include/sys/cdefs.h /usr/include/gnu/stubs.h \
 /usr/lib/gcc-lib/i386-redhat-linux/3.2.2/include/stddef.h \
 /usr/lib/gcc-lib/i386-redhat-linux/3.2.2/include/stdarg.h \
 /usr/include/bits/types.h /usr/include/libio.h \
 /usr/include/_G_config.h /usr/include/bits/stdio_lim.h \
 /usr/include/time.h /usr/include/bits/time.h /usr/include/string.h \
 /usr/include/ctype.h /usr/include/endian.h /usr/include/bits/endian.h \
 ../include/common.h ../include/char.h ../include/char_base.h \
 ../include/skill.h ../include/util.h /usr/include/sys/time.h \
 /usr/include/sys/select.h /usr/include/bits/select.h \
 /usr/include/bits/sigset.h /usr/include/stdlib.h \
 /usr/include/sys/types.h /usr/include/sys/sysmacros.h \
 /usr/include/alloca.h ../include/title.h ../include/addressbook.h \
 ../include/net.h /usr/include/netinet/in.h \
 /usr/lib/gcc-lib/i386-redhat-linux/3.2.2/include/limits.h \
 /usr/lib/gcc-lib/i386-redhat-linux/3.2.2/include/syslimits.h \
 /usr/include/limits.h /usr/include/bits/posix1_lim.h \
 /usr/include/bits/local_lim.h /usr/include/linux/limits.h \
 /usr/include/bits/posix2_lim.h /usr/include/stdint.h \
 /usr/include/bits/wordsize.h /usr/include/bits/socket.h \
 /usr/include/bits/sockaddr.h /usr/include/asm/socket.h \
 /usr/include/asm/sockios.h /usr/include/bits/in.h \
 /usr/include/bits/byteswap.h /usr/include/signal.h \
 /usr/include/bits/signum.h /usr/include/bits/siginfo.h \
 /usr/include/bits/sigaction.h /usr/include/bits/sigcontext.h \
 /usr/include/asm/sigcontext.h /usr/include/bits/sigstack.h \
 ../include/link.h ../include/char_data.h ../include/item.h \
 ../include/buf.h ../include/npcutil.h ../include/object.h \
 ../include/handletime.h ../include/chatmagic.h \
 ../include/configfile.h ../include/readmap.h ../include/map_deal.h \
 ../include/lssproto_serv.h ../include/lssproto_util.h \
 /usr/include/strings.h /usr/include/unistd.h \
 /usr/include/bits/posix_opt.h /usr/include/bits/confname.h \
 /usr/include/getopt.h ../include/log.h ../include/battle.h \
 ../include/pet.h ../include/enemy.h ../include/encount.h \
 ../include/magic_base.h ../include/magic.h ../include/pet_skill.h \
 ../include/item_gen.h
event.o: event.c /usr/include/stdio.h /usr/include/features.h \
 /usr/include/sys/cdefs.h /usr/include/gnu/stubs.h \
 /usr/lib/gcc-lib/i386-redhat-linux/3.2.2/include/stddef.h \
 /usr/lib/gcc-lib/i386-redhat-linux/3.2.2/include/stdarg.h \
 /usr/include/bits/types.h /usr/include/libio.h \
 /usr/include/_G_config.h /usr/include/bits/stdio_lim.h \
 ../include/object.h ../include/common.h ../include/char_base.h \
 ../include/skill.h ../include/util.h /usr/include/sys/time.h \
 /usr/include/time.h /usr/include/bits/time.h \
 /usr/include/sys/select.h /usr/include/bits/select.h \
 /usr/include/bits/sigset.h /usr/include/stdlib.h \
 /usr/include/sys/types.h /usr/include/endian.h \
 /usr/include/bits/endian.h /usr/include/sys/sysmacros.h \
 /usr/include/alloca.h ../include/title.h ../include/addressbook.h \
 ../include/net.h /usr/include/netinet/in.h \
 /usr/lib/gcc-lib/i386-redhat-linux/3.2.2/include/limits.h \
 /usr/lib/gcc-lib/i386-redhat-linux/3.2.2/include/syslimits.h \
 /usr/include/limits.h /usr/include/bits/posix1_lim.h \
 /usr/include/bits/local_lim.h /usr/include/linux/limits.h \
 /usr/include/bits/posix2_lim.h /usr/include/stdint.h \
 /usr/include/bits/wordsize.h /usr/include/bits/socket.h \
 /usr/include/bits/sockaddr.h /usr/include/asm/socket.h \
 /usr/include/asm/sockios.h /usr/include/bits/in.h \
 /usr/include/bits/byteswap.h /usr/include/signal.h \
 /usr/include/bits/signum.h /usr/include/bits/siginfo.h \
 /usr/include/bits/sigaction.h /usr/include/bits/sigcontext.h \
 /usr/include/asm/sigcontext.h /usr/include/bits/sigstack.h \
 ../include/link.h ../include/char.h ../include/char_data.h \
 ../include/map_warppoint.h \
 ../include/item.h ../include/readmap.h ../include/event.h \
 ../include/npc_warp.h ../include/npc_npcenemy.h 
char_walk.o: char_walk.c /usr/include/stdio.h /usr/include/features.h \
 /usr/include/sys/cdefs.h /usr/include/gnu/stubs.h \
 /usr/lib/gcc-lib/i386-redhat-linux/3.2.2/include/stddef.h \
 /usr/lib/gcc-lib/i386-redhat-linux/3.2.2/include/stdarg.h \
 /usr/include/bits/types.h /usr/include/libio.h \
 /usr/include/_G_config.h /usr/include/bits/stdio_lim.h \
 /usr/include/ctype.h /usr/include/endian.h /usr/include/bits/endian.h \
 ../include/common.h ../include/handletime.h /usr/include/sys/time.h \
 /usr/include/time.h /usr/include/bits/time.h \
 /usr/include/sys/select.h /usr/include/bits/select.h \
 /usr/include/bits/sigset.h ../include/object.h ../include/char_base.h \
 ../include/skill.h ../include/util.h /usr/include/stdlib.h \
 /usr/include/sys/types.h /usr/include/sys/sysmacros.h \
 /usr/include/alloca.h ../include/title.h ../include/addressbook.h \
 ../include/net.h /usr/include/netinet/in.h \
 /usr/lib/gcc-lib/i386-redhat-linux/3.2.2/include/limits.h \
 /usr/lib/gcc-lib/i386-redhat-linux/3.2.2/include/syslimits.h \
 /usr/include/limits.h /usr/include/bits/posix1_lim.h \
 /usr/include/bits/local_lim.h /usr/include/linux/limits.h \
 /usr/include/bits/posix2_lim.h /usr/include/stdint.h \
 /usr/include/bits/wordsize.h /usr/include/bits/socket.h \
 /usr/include/bits/sockaddr.h /usr/include/asm/socket.h \
 /usr/include/asm/sockios.h /usr/include/bits/in.h \
 /usr/include/bits/byteswap.h /usr/include/signal.h \
 /usr/include/bits/signum.h /usr/include/bits/siginfo.h \
 /usr/include/bits/sigaction.h /usr/include/bits/sigcontext.h \
 /usr/include/asm/sigcontext.h /usr/include/bits/sigstack.h \
 ../include/link.h ../include/char.h ../include/char_data.h \
 ../include/item.h ../include/char_event.h ../include/lssproto_serv.h \
 ../include/lssproto_util.h /usr/include/string.h \
 /usr/include/strings.h /usr/include/unistd.h \
 /usr/include/bits/posix_opt.h /usr/include/bits/confname.h \
 /usr/include/getopt.h ../include/readmap.h ../include/map_deal.h \
 ../include/npccreate.h ../include/encount.h ../include/npcutil.h \
 ../include/battle.h
encount.o: encount.c /usr/include/stdio.h /usr/include/features.h \
 /usr/include/sys/cdefs.h /usr/include/gnu/stubs.h \
 /usr/lib/gcc-lib/i386-redhat-linux/3.2.2/include/stddef.h \
 /usr/lib/gcc-lib/i386-redhat-linux/3.2.2/include/stdarg.h \
 /usr/include/bits/types.h /usr/include/libio.h \
 /usr/include/_G_config.h /usr/include/bits/stdio_lim.h \
 /usr/include/string.h /usr/include/math.h \
 /usr/include/bits/huge_val.h /usr/include/bits/mathdef.h \
 /usr/include/bits/mathcalls.h \
 /usr/lib/gcc-lib/i386-redhat-linux/3.2.2/include/float.h \
 ../include/common.h ../include/util.h /usr/include/sys/time.h \
 /usr/include/time.h /usr/include/bits/time.h \
 /usr/include/sys/select.h /usr/include/bits/select.h \
 /usr/include/bits/sigset.h /usr/include/stdlib.h \
 /usr/include/sys/types.h /usr/include/endian.h \
 /usr/include/bits/endian.h /usr/include/sys/sysmacros.h \
 /usr/include/alloca.h ../include/buf.h ../include/char_base.h \
 ../include/skill.h ../include/title.h ../include/addressbook.h \
 ../include/net.h /usr/include/netinet/in.h \
 /usr/lib/gcc-lib/i386-redhat-linux/3.2.2/include/limits.h \
 /usr/lib/gcc-lib/i386-redhat-linux/3.2.2/include/syslimits.h \
 /usr/include/limits.h /usr/include/bits/posix1_lim.h \
 /usr/include/bits/local_lim.h /usr/include/linux/limits.h \
 /usr/include/bits/posix2_lim.h /usr/include/stdint.h \
 /usr/include/bits/wordsize.h /usr/include/bits/socket.h \
 /usr/include/bits/sockaddr.h /usr/include/asm/socket.h \
 /usr/include/asm/sockios.h /usr/include/bits/in.h \
 /usr/include/bits/byteswap.h /usr/include/signal.h \
 /usr/include/bits/signum.h /usr/include/bits/siginfo.h \
 /usr/include/bits/sigaction.h /usr/include/bits/sigcontext.h \
 /usr/include/asm/sigcontext.h /usr/include/bits/sigstack.h \
 ../include/link.h ../include/char.h ../include/char_data.h \
 ../include/item.h ../include/configfile.h ../include/encount.h \
 ../include/enemy.h
pet.o: pet.c /usr/include/stdio.h /usr/include/features.h \
 /usr/include/sys/cdefs.h /usr/include/gnu/stubs.h \
 /usr/lib/gcc-lib/i386-redhat-linux/3.2.2/include/stddef.h \
 /usr/lib/gcc-lib/i386-redhat-linux/3.2.2/include/stdarg.h \
 /usr/include/bits/types.h /usr/include/libio.h \
 /usr/include/_G_config.h /usr/include/bits/stdio_lim.h \
 ../include/char_base.h ../include/skill.h ../include/common.h \
 ../include/util.h /usr/include/sys/time.h /usr/include/time.h \
 /usr/include/bits/time.h /usr/include/sys/select.h \
 /usr/include/bits/select.h /usr/include/bits/sigset.h \
 /usr/include/stdlib.h /usr/include/sys/types.h /usr/include/endian.h \
 /usr/include/bits/endian.h /usr/include/sys/sysmacros.h \
 /usr/include/alloca.h ../include/title.h ../include/addressbook.h \
 ../include/net.h /usr/include/netinet/in.h \
 /usr/lib/gcc-lib/i386-redhat-linux/3.2.2/include/limits.h \
 /usr/lib/gcc-lib/i386-redhat-linux/3.2.2/include/syslimits.h \
 /usr/include/limits.h /usr/include/bits/posix1_lim.h \
 /usr/include/bits/local_lim.h /usr/include/linux/limits.h \
 /usr/include/bits/posix2_lim.h /usr/include/stdint.h \
 /usr/include/bits/wordsize.h /usr/include/bits/socket.h \
 /usr/include/bits/sockaddr.h /usr/include/asm/socket.h \
 /usr/include/asm/sockios.h /usr/include/bits/in.h \
 /usr/include/bits/byteswap.h /usr/include/signal.h \
 /usr/include/bits/signum.h /usr/include/bits/siginfo.h \
 /usr/include/bits/sigaction.h /usr/include/bits/sigcontext.h \
 /usr/include/asm/sigcontext.h /usr/include/bits/sigstack.h \
 ../include/link.h ../include/char.h ../include/char_data.h \
 ../include/item.h ../include/object.h ../include/readmap.h \
 ../include/map_deal.h ../include/lssproto_serv.h \
 ../include/lssproto_util.h /usr/include/string.h \
 /usr/include/strings.h /usr/include/unistd.h \
 /usr/include/bits/posix_opt.h /usr/include/bits/confname.h \
 /usr/include/getopt.h ../include/handletime.h ../include/pet.h \
 ../include/battle.h ../include/petmail.h ../include/log.h
enemy.o: enemy.c /usr/include/stdio.h /usr/include/features.h \
 /usr/include/sys/cdefs.h /usr/include/gnu/stubs.h \
 /usr/lib/gcc-lib/i386-redhat-linux/3.2.2/include/stddef.h \
 /usr/lib/gcc-lib/i386-redhat-linux/3.2.2/include/stdarg.h \
 /usr/include/bits/types.h /usr/include/libio.h \
 /usr/include/_G_config.h /usr/include/bits/stdio_lim.h \
 /usr/include/string.h ../include/common.h ../include/util.h \
 /usr/include/sys/time.h /usr/include/time.h /usr/include/bits/time.h \
 /usr/include/sys/select.h /usr/include/bits/select.h \
 /usr/include/bits/sigset.h /usr/include/stdlib.h \
 /usr/include/sys/types.h /usr/include/endian.h \
 /usr/include/bits/endian.h /usr/include/sys/sysmacros.h \
 /usr/include/alloca.h ../include/buf.h ../include/char_base.h \
 ../include/skill.h ../include/title.h ../include/addressbook.h \
 ../include/net.h /usr/include/netinet/in.h \
 /usr/lib/gcc-lib/i386-redhat-linux/3.2.2/include/limits.h \
 /usr/lib/gcc-lib/i386-redhat-linux/3.2.2/include/syslimits.h \
 /usr/include/limits.h /usr/include/bits/posix1_lim.h \
 /usr/include/bits/local_lim.h /usr/include/linux/limits.h \
 /usr/include/bits/posix2_lim.h /usr/include/stdint.h \
 /usr/include/bits/wordsize.h /usr/include/bits/socket.h \
 /usr/include/bits/sockaddr.h /usr/include/asm/socket.h \
 /usr/include/asm/sockios.h /usr/include/bits/in.h \
 /usr/include/bits/byteswap.h /usr/include/signal.h \
 /usr/include/bits/signum.h /usr/include/bits/siginfo.h \
 /usr/include/bits/sigaction.h /usr/include/bits/sigcontext.h \
 /usr/include/asm/sigcontext.h /usr/include/bits/sigstack.h \
 ../include/link.h ../include/char.h ../include/char_data.h \
 ../include/item.h ../include/configfile.h ../include/encount.h \
 ../include/enemy.h ../include/pet.h ../include/enemyexptbl.h \
 ../include/petmail.h ../include/battle.h ../include/pet_skillinfo.h \
 ../include/anim_tbl.h
pet_event.o: pet_event.c /usr/include/stdio.h /usr/include/features.h \
 /usr/include/sys/cdefs.h /usr/include/gnu/stubs.h \
 /usr/lib/gcc-lib/i386-redhat-linux/3.2.2/include/stddef.h \
 /usr/lib/gcc-lib/i386-redhat-linux/3.2.2/include/stdarg.h \
 /usr/include/bits/types.h /usr/include/libio.h \
 /usr/include/_G_config.h /usr/include/bits/stdio_lim.h \
 /usr/include/stdlib.h /usr/include/sys/types.h /usr/include/time.h \
 /usr/include/endian.h /usr/include/bits/endian.h \
 /usr/include/sys/select.h /usr/include/bits/select.h \
 /usr/include/bits/sigset.h /usr/include/sys/sysmacros.h \
 /usr/include/alloca.h ../include/common.h ../include/object.h \
 ../include/char_base.h ../include/skill.h ../include/util.h \
 /usr/include/sys/time.h /usr/include/bits/time.h ../include/title.h \
 ../include/addressbook.h ../include/net.h /usr/include/netinet/in.h \
 /usr/lib/gcc-lib/i386-redhat-linux/3.2.2/include/limits.h \
 /usr/lib/gcc-lib/i386-redhat-linux/3.2.2/include/syslimits.h \
 /usr/include/limits.h /usr/include/bits/posix1_lim.h \
 /usr/include/bits/local_lim.h /usr/include/linux/limits.h \
 /usr/include/bits/posix2_lim.h /usr/include/stdint.h \
 /usr/include/bits/wordsize.h /usr/include/bits/socket.h \
 /usr/include/bits/sockaddr.h /usr/include/asm/socket.h \
 /usr/include/asm/sockios.h /usr/include/bits/in.h \
 /usr/include/bits/byteswap.h /usr/include/signal.h \
 /usr/include/bits/signum.h /usr/include/bits/siginfo.h \
 /usr/include/bits/sigaction.h /usr/include/bits/sigcontext.h \
 /usr/include/asm/sigcontext.h /usr/include/bits/sigstack.h \
 ../include/link.h ../include/char.h ../include/char_data.h \
 ../include/item.h ../include/configfile.h ../include/handletime.h \
 ../include/pet_event.h ../include/npcutil.h ../include/log.h
char_talk.o: char_talk.c /usr/include/stdio.h /usr/include/features.h \
 /usr/include/sys/cdefs.h /usr/include/gnu/stubs.h \
 /usr/lib/gcc-lib/i386-redhat-linux/3.2.2/include/stddef.h \
 /usr/lib/gcc-lib/i386-redhat-linux/3.2.2/include/stdarg.h \
 /usr/include/bits/types.h /usr/include/libio.h \
 /usr/include/_G_config.h /usr/include/bits/stdio_lim.h \
 /usr/include/ctype.h /usr/include/endian.h /usr/include/bits/endian.h \
 /usr/include/string.h ../include/readmap.h ../include/common.h \
 ../include/util.h /usr/include/sys/time.h /usr/include/time.h \
 /usr/include/bits/time.h /usr/include/sys/select.h \
 /usr/include/bits/select.h /usr/include/bits/sigset.h \
 /usr/include/stdlib.h /usr/include/sys/types.h \
 /usr/include/sys/sysmacros.h /usr/include/alloca.h \
 ../include/object.h ../include/char.h ../include/char_base.h \
 ../include/skill.h ../include/title.h ../include/addressbook.h \
 ../include/net.h /usr/include/netinet/in.h \
 /usr/lib/gcc-lib/i386-redhat-linux/3.2.2/include/limits.h \
 /usr/lib/gcc-lib/i386-redhat-linux/3.2.2/include/syslimits.h \
 /usr/include/limits.h /usr/include/bits/posix1_lim.h \
 /usr/include/bits/local_lim.h /usr/include/linux/limits.h \
 /usr/include/bits/posix2_lim.h /usr/include/stdint.h \
 /usr/include/bits/wordsize.h /usr/include/bits/socket.h \
 /usr/include/bits/sockaddr.h /usr/include/asm/socket.h \
 /usr/include/asm/sockios.h /usr/include/bits/in.h \
 /usr/include/bits/byteswap.h /usr/include/signal.h \
 /usr/include/bits/signum.h /usr/include/bits/siginfo.h \
 /usr/include/bits/sigaction.h /usr/include/bits/sigcontext.h \
 /usr/include/asm/sigcontext.h /usr/include/bits/sigstack.h \
 ../include/link.h ../include/char_data.h ../include/item.h \
 ../include/chatmagic.h ../include/battle.h ../include/log.h \
 ../include/configfile.h ../include/lssproto_serv.h \
 ../include/lssproto_util.h /usr/include/strings.h \
 /usr/include/unistd.h /usr/include/bits/posix_opt.h \
 /usr/include/bits/confname.h /usr/include/getopt.h \
 ../include/family.h
char_party.o: char_party.c /usr/include/stdio.h \
 /usr/include/features.h /usr/include/sys/cdefs.h \
 /usr/include/gnu/stubs.h \
 /usr/lib/gcc-lib/i386-redhat-linux/3.2.2/include/stddef.h \
 /usr/lib/gcc-lib/i386-redhat-linux/3.2.2/include/stdarg.h \
 /usr/include/bits/types.h /usr/include/libio.h \
 /usr/include/_G_config.h /usr/include/bits/stdio_lim.h \
 ../include/readmap.h ../include/common.h ../include/util.h \
 /usr/include/sys/time.h /usr/include/time.h /usr/include/bits/time.h \
 /usr/include/sys/select.h /usr/include/bits/select.h \
 /usr/include/bits/sigset.h /usr/include/stdlib.h \
 /usr/include/sys/types.h /usr/include/endian.h \
 /usr/include/bits/endian.h /usr/include/sys/sysmacros.h \
 /usr/include/alloca.h ../include/object.h ../include/char.h \
 ../include/char_base.h ../include/skill.h ../include/title.h \
 ../include/addressbook.h ../include/net.h /usr/include/netinet/in.h \
 /usr/lib/gcc-lib/i386-redhat-linux/3.2.2/include/limits.h \
 /usr/lib/gcc-lib/i386-redhat-linux/3.2.2/include/syslimits.h \
 /usr/include/limits.h /usr/include/bits/posix1_lim.h \
 /usr/include/bits/local_lim.h /usr/include/linux/limits.h \
 /usr/include/bits/posix2_lim.h /usr/include/stdint.h \
 /usr/include/bits/wordsize.h /usr/include/bits/socket.h \
 /usr/include/bits/sockaddr.h /usr/include/asm/socket.h \
 /usr/include/asm/sockios.h /usr/include/bits/in.h \
 /usr/include/bits/byteswap.h /usr/include/signal.h \
 /usr/include/bits/signum.h /usr/include/bits/siginfo.h \
 /usr/include/bits/sigaction.h /usr/include/bits/sigcontext.h \
 /usr/include/asm/sigcontext.h /usr/include/bits/sigstack.h \
 ../include/link.h ../include/char_data.h ../include/item.h \
 ../include/battle.h ../include/lssproto_serv.h \
 ../include/lssproto_util.h /usr/include/string.h \
 /usr/include/strings.h /usr/include/unistd.h \
 /usr/include/bits/posix_opt.h /usr/include/bits/confname.h \
 /usr/include/getopt.h ../include/npcutil.h ../include/npc_bus.h \
 ../include/init.h
char_item.o: char_item.c /usr/include/stdio.h /usr/include/features.h \
 /usr/include/sys/cdefs.h /usr/include/gnu/stubs.h \
 /usr/lib/gcc-lib/i386-redhat-linux/3.2.2/include/stddef.h \
 /usr/lib/gcc-lib/i386-redhat-linux/3.2.2/include/stdarg.h \
 /usr/include/bits/types.h /usr/include/libio.h \
 /usr/include/_G_config.h /usr/include/bits/stdio_lim.h \
 ../include/readmap.h ../include/common.h ../include/util.h \
 /usr/include/sys/time.h /usr/include/time.h /usr/include/bits/time.h \
 /usr/include/sys/select.h /usr/include/bits/select.h \
 /usr/include/bits/sigset.h /usr/include/stdlib.h \
 /usr/include/sys/types.h /usr/include/endian.h \
 /usr/include/bits/endian.h /usr/include/sys/sysmacros.h \
 /usr/include/alloca.h ../include/map_deal.h ../include/object.h \
 ../include/char.h ../include/char_base.h ../include/skill.h \
 ../include/title.h ../include/addressbook.h ../include/net.h \
 /usr/include/netinet/in.h \
 /usr/lib/gcc-lib/i386-redhat-linux/3.2.2/include/limits.h \
 /usr/lib/gcc-lib/i386-redhat-linux/3.2.2/include/syslimits.h \
 /usr/include/limits.h /usr/include/bits/posix1_lim.h \
 /usr/include/bits/local_lim.h /usr/include/linux/limits.h \
 /usr/include/bits/posix2_lim.h /usr/include/stdint.h \
 /usr/include/bits/wordsize.h /usr/include/bits/socket.h \
 /usr/include/bits/sockaddr.h /usr/include/asm/socket.h \
 /usr/include/asm/sockios.h /usr/include/bits/in.h \
 /usr/include/bits/byteswap.h /usr/include/signal.h \
 /usr/include/bits/signum.h /usr/include/bits/siginfo.h \
 /usr/include/bits/sigaction.h /usr/include/bits/sigcontext.h \
 /usr/include/asm/sigcontext.h /usr/include/bits/sigstack.h \
 ../include/link.h ../include/char_data.h ../include/item.h \
 ../include/lssproto_serv.h ../include/lssproto_util.h \
 /usr/include/string.h /usr/include/strings.h /usr/include/unistd.h \
 /usr/include/bits/posix_opt.h /usr/include/bits/confname.h \
 /usr/include/getopt.h ../include/handletime.h ../include/log.h \
 ../include/item_event.h ../include/battle.h
petmail.o: petmail.c /usr/include/stdio.h /usr/include/features.h \
 /usr/include/sys/cdefs.h /usr/include/gnu/stubs.h \
 /usr/lib/gcc-lib/i386-redhat-linux/3.2.2/include/stddef.h \
 /usr/lib/gcc-lib/i386-redhat-linux/3.2.2/include/stdarg.h \
 /usr/include/bits/types.h /usr/include/libio.h \
 /usr/include/_G_config.h /usr/include/bits/stdio_lim.h \
 ../include/configfile.h ../include/common.h ../include/buf.h \
 ../include/char_base.h ../include/skill.h ../include/util.h \
 /usr/include/sys/time.h /usr/include/time.h /usr/include/bits/time.h \
 /usr/include/sys/select.h /usr/include/bits/select.h \
 /usr/include/bits/sigset.h /usr/include/stdlib.h \
 /usr/include/sys/types.h /usr/include/endian.h \
 /usr/include/bits/endian.h /usr/include/sys/sysmacros.h \
 /usr/include/alloca.h ../include/title.h ../include/addressbook.h \
 ../include/net.h /usr/include/netinet/in.h \
 /usr/lib/gcc-lib/i386-redhat-linux/3.2.2/include/limits.h \
 /usr/lib/gcc-lib/i386-redhat-linux/3.2.2/include/syslimits.h \
 /usr/include/limits.h /usr/include/bits/posix1_lim.h \
 /usr/include/bits/local_lim.h /usr/include/linux/limits.h \
 /usr/include/bits/posix2_lim.h /usr/include/stdint.h \
 /usr/include/bits/wordsize.h /usr/include/bits/socket.h \
 /usr/include/bits/sockaddr.h /usr/include/asm/socket.h \
 /usr/include/asm/sockios.h /usr/include/bits/in.h \
 /usr/include/bits/byteswap.h /usr/include/signal.h \
 /usr/include/bits/signum.h /usr/include/bits/siginfo.h \
 /usr/include/bits/sigaction.h /usr/include/bits/sigcontext.h \
 /usr/include/asm/sigcontext.h /usr/include/bits/sigstack.h \
 ../include/link.h ../include/char.h ../include/char_data.h \
 ../include/item.h ../include/battle.h ../include/handletime.h \
 ../include/map_deal.h ../include/lssproto_serv.h \
 ../include/lssproto_util.h /usr/include/string.h \
 /usr/include/strings.h /usr/include/unistd.h \
 /usr/include/bits/posix_opt.h /usr/include/bits/confname.h \
 /usr/include/getopt.h ../include/pet.h ../include/petmail.h \
 ../include/npcutil.h ../include/log.h
trade.o: trade.c /usr/include/stdio.h /usr/include/features.h \
 /usr/include/sys/cdefs.h /usr/include/gnu/stubs.h \
 /usr/lib/gcc-lib/i386-redhat-linux/3.2.2/include/stddef.h \
 /usr/lib/gcc-lib/i386-redhat-linux/3.2.2/include/stdarg.h \
 /usr/include/bits/types.h /usr/include/libio.h \
 /usr/include/_G_config.h /usr/include/bits/stdio_lim.h \
 /usr/include/string.h /usr/include/ctype.h /usr/include/endian.h \
 /usr/include/bits/endian.h ../include/readmap.h ../include/common.h \
 ../include/util.h /usr/include/sys/time.h /usr/include/time.h \
 /usr/include/bits/time.h /usr/include/sys/select.h \
 /usr/include/bits/select.h /usr/include/bits/sigset.h \
 /usr/include/stdlib.h /usr/include/sys/types.h \
 /usr/include/sys/sysmacros.h /usr/include/alloca.h \
 ../include/object.h ../include/char.h ../include/char_base.h \
 ../include/skill.h ../include/title.h ../include/addressbook.h \
 ../include/net.h /usr/include/netinet/in.h \
 /usr/lib/gcc-lib/i386-redhat-linux/3.2.2/include/limits.h \
 /usr/lib/gcc-lib/i386-redhat-linux/3.2.2/include/syslimits.h \
 /usr/include/limits.h /usr/include/bits/posix1_lim.h \
 /usr/include/bits/local_lim.h /usr/include/linux/limits.h \
 /usr/include/bits/posix2_lim.h /usr/include/stdint.h \
 /usr/include/bits/wordsize.h /usr/include/bits/socket.h \
 /usr/include/bits/sockaddr.h /usr/include/asm/socket.h \
 /usr/include/asm/sockios.h /usr/include/bits/in.h \
 /usr/include/bits/byteswap.h /usr/include/signal.h \
 /usr/include/bits/signum.h /usr/include/bits/siginfo.h \
 /usr/include/bits/sigaction.h /usr/include/bits/sigcontext.h \
 /usr/include/asm/sigcontext.h /usr/include/bits/sigstack.h \
 ../include/link.h ../include/char_data.h ../include/item.h \
 ../include/lssproto_serv.h ../include/lssproto_util.h \
 /usr/include/strings.h /usr/include/unistd.h \
 /usr/include/bits/posix_opt.h /usr/include/bits/confname.h \
 /usr/include/getopt.h ../include/npcutil.h ../include/trade.h \
 ../include/log.h ../include/handletime.h ../include/buf.h \
 ../include/battle.h ../include/npc_bus.h ../include/char_talk.h
family.o: family.c /usr/include/stdio.h /usr/include/features.h \
 /usr/include/sys/cdefs.h /usr/include/gnu/stubs.h \
 /usr/lib/gcc-lib/i386-redhat-linux/3.2.2/include/stddef.h \
 /usr/lib/gcc-lib/i386-redhat-linux/3.2.2/include/stdarg.h \
 /usr/include/bits/types.h /usr/include/libio.h \
 /usr/include/_G_config.h /usr/include/bits/stdio_lim.h \
 /usr/include/string.h /usr/include/ctype.h /usr/include/endian.h \
 /usr/include/bits/endian.h ../include/readmap.h ../include/common.h \
 ../include/util.h /usr/include/sys/time.h /usr/include/time.h \
 /usr/include/bits/time.h /usr/include/sys/select.h \
 /usr/include/bits/select.h /usr/include/bits/sigset.h \
 /usr/include/stdlib.h /usr/include/sys/types.h \
 /usr/include/sys/sysmacros.h /usr/include/alloca.h \
 ../include/object.h ../include/char.h ../include/char_base.h \
 ../include/skill.h ../include/title.h ../include/addressbook.h \
 ../include/net.h /usr/include/netinet/in.h \
 /usr/lib/gcc-lib/i386-redhat-linux/3.2.2/include/limits.h \
 /usr/lib/gcc-lib/i386-redhat-linux/3.2.2/include/syslimits.h \
 /usr/include/limits.h /usr/include/bits/posix1_lim.h \
 /usr/include/bits/local_lim.h /usr/include/linux/limits.h \
 /usr/include/bits/posix2_lim.h /usr/include/stdint.h \
 /usr/include/bits/wordsize.h /usr/include/bits/socket.h \
 /usr/include/bits/sockaddr.h /usr/include/asm/socket.h \
 /usr/include/asm/sockios.h /usr/include/bits/in.h \
 /usr/include/bits/byteswap.h /usr/include/signal.h \
 /usr/include/bits/signum.h /usr/include/bits/siginfo.h \
 /usr/include/bits/sigaction.h /usr/include/bits/sigcontext.h \
 /usr/include/asm/sigcontext.h /usr/include/bits/sigstack.h \
 ../include/link.h ../include/char_data.h ../include/item.h \
 ../include/lssproto_serv.h ../include/lssproto_util.h \
 /usr/include/strings.h /usr/include/unistd.h \
 /usr/include/bits/posix_opt.h /usr/include/bits/confname.h \
 /usr/include/getopt.h ../include/saacproto_cli.h \
 ../include/saacproto_util.h ../include/npcutil.h ../include/family.h \
 ../include/log.h ../include/handletime.h ../include/buf.h \
 ../include/battle.h ../include/npc_bus.h ../include/char_talk.h
